baseURL = "https://www.jamieb.com"
languageCode = "en-us"
title = "Jamie Brummell"
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "Blog"
    weight = 0
    url = "/post"

[params]
  Name = "Jamie Brummell"
  HeaderUsername = "jamieb"
  HeaderHostname = "jamieb.com"
  About = "An Information Security Professional in the UK. And here's a bit more text to check that the alignment is working."
  ProfilePicture = "https://miro.medium.com/max/3150/2*Kq9UmDkUjo45SDhCX6XB0Q.jpeg"
  TwitterID = "jamiebrummell"
  LinkedInID = "jamiebrummell"
  GithubID = "jamie-b"
[submodule "themes/hugo-theme-nix"]
  path = "themes/hugo-theme-nix"
  url = "https://github.com/LordMathis/hugo-theme-nix.git"
