baseURL = "https://www.jamieb.com"
languageCode = "en-us"
title = "Jamie Brummell"
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "Blog"
    weight = 0
    url = "/post"

[params]
  Name = "Jamie Brummell"
  HeaderUsername = "jamieb"
  HeaderHostname = "jamieb.com"
  About = "I am an information security consultant, based in London, working for a Silicon Valley headquartered cybersecurity company. I primarily consult with UK-based clients in the financial services & insurance industries."
  ProfilePicture = "https://pbs.twimg.com/profile_images/1030066755132108800/p5T3WQwJ_400x400.jpg"
  GithubID = "jamie-b"
  TwitterID = "jamiebrummell"
  LinkedInID = "jamiebrummell"
[submodule "themes/hugo-theme-nix"]
  path = "themes/hugo-theme-nix"
  url = "https://github.com/LordMathis/hugo-theme-nix.git"